version: '3.8'
services:

  mongodb:
    image: mongo:6.0.2-focal

  api:
    image: yasithab/demo-api:1.0.0
    platform: linux/amd64
    ports:
      - '80:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb